require "../spec_helper"

# `Oas.parse_file` turns an OpenAPI/Swagger document into requests. Everything in the file is
# written by hand or generated by someone else's tool, so every failure here has to arrive as a
# `Gori::Error` — that is the only class `Import.import_file` passes through cleanly and the
# only one `CLI.run` turns into a message instead of a backtrace.
private def with_spec(body : String, ext : String, &)
  path = File.tempname("gori-oas", ext)
  File.write(path, body)
  begin
    yield path
  ensure
    File.delete?(path)
  end
end

describe Gori::Import::Oas do
  it "imports an ordinary spec" do
    body = <<-YAML
      openapi: 3.0.0
      info: {title: t, version: "1"}
      servers:
        - url: "https://api.example.test/v1"
      paths:
        /a:
          get:
            responses: {"200": {description: ok}}
      YAML
    with_spec(body, ".yaml") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.size.should eq(1)
    end
  end

  it "puts generated query parameters before a path fragment" do
    body = <<-JSON
      {
        "openapi": "3.0.3",
        "info": {"title": "t", "version": "1"},
        "servers": [{"url": "https://api.example.test/v1"}],
        "paths": {
          "/search#client-fragment": {
            "get": {
              "parameters": [{"name": "q", "in": "query", "required": true,
                              "schema": {"type": "string"}}],
              "responses": {"200": {"description": "ok"}}
            }
          }
        }
      }
      JSON
    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.first.request.target.should eq("/v1/search?q=q")
    end
  end

  it "fills a parameter from its example, examples, default or enum before synthesizing one" do
    body = <<-JSON
      {
        "openapi": "3.0.3",
        "info": {"title": "t", "version": "1"},
        "servers": [{"url": "https://api.example.test"}],
        "paths": {
          "/users/{id}": {
            "get": {
              "parameters": [
                {"name": "id", "in": "path", "required": true, "example": 43, "schema": {"type": "integer"}},
                {"name": "sort", "in": "query", "required": true, "schema": {"type": "string", "enum": ["asc", "desc"]}},
                {"name": "lang", "in": "query", "required": true, "examples": {"ko": {"value": "ko"}}},
                {"name": "page", "in": "query", "required": true, "schema": {"type": "integer", "default": 5}},
                {"name": "q", "in": "query", "required": true, "schema": {"type": "string"}},
                {"name": "o", "in": "query", "required": true, "example": {"k": 1}, "schema": {"type": "string", "enum": [null, "x"]}}
              ],
              "responses": {"200": {"description": "ok"}}
            }
          }
        }
      }
      JSON
    with_spec(body, ".json") do |path|
      target = Gori::Import::Oas.parse_file(path).flows.first.request.target
      target.should eq("/users/43?sort=asc&lang=ko&page=5&q=q&o=x")
    end
  end

  it "percent-encodes an example spliced into a path segment" do
    body = <<-JSON
      {"openapi": "3.0.3", "info": {"title": "t", "version": "1"},
       "servers": [{"url": "https://api.example.test"}],
       "paths": {"/users/{name}/a": {"get": {
         "parameters": [{"name": "name", "in": "path", "required": true, "example": "john doe#b"}],
         "responses": {"200": {"description": "ok"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      Gori::Import::Oas.parse_file(path).flows.first.request.target.should eq("/users/john%20doe%23b/a")
    end
  end

  it "resolves local parameter, requestBody, and schema refs at path and operation level" do
    body = <<-JSON
      {
        "openapi": "3.0.3",
        "info": {"title": "t", "version": "1"},
        "servers": [{"url": "http://api.example.test/v1"}],
        "components": {
          "parameters": {
            "UserId": {"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}},
            "ApiVer": {"name": "api_version", "in": "query", "required": true, "schema": {"type": "string"}}
          },
          "requestBodies": {
            "User": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/User"}}}}
          },
          "schemas": {"User": {"type": "object"}, "UserList": {"type": "array"}}
        },
        "paths": {
          "/users/{id}": {
            "parameters": [{"$ref": "#/components/parameters/UserId"}],
            "get": {
              "parameters": [{"$ref": "#/components/parameters/ApiVer"}],
              "responses": {"200": {"description": "ok"}}
            },
            "put": {
              "requestBody": {"$ref": "#/components/requestBodies/User"},
              "responses": {"200": {"description": "ok"}}
            }
          },
          "/users": {
            "post": {
              "requestBody": {"content": {"application/json": {"schema": {"$ref": "#/components/schemas/UserList"}}}},
              "responses": {"200": {"description": "ok"}}
            }
          }
        }
      }
      JSON

    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.size.should eq(3)
      get = String.new(result.flows[0].request.head)
      put = String.new(result.flows[1].request.head)
      get.should contain("GET /v1/users/1?api_version=api_version HTTP/1.1")
      put.should contain("PUT /v1/users/1 HTTP/1.1")
      put.should contain("Content-Type: application/json\r\n")
      String.new(result.flows[1].request.body.not_nil!).should eq("{}")
      String.new(result.flows[2].request.body.not_nil!).should eq("[]")
    end
  end

  it "imports Swagger 2 host, basePath, body, formData, and consumes" do
    body = <<-JSON
      {
        "swagger": "2.0",
        "info": {"title": "t", "version": "1"},
        "host": "127.0.0.1:18501",
        "basePath": "/v1",
        "schemes": ["http"],
        "consumes": ["application/json"],
        "definitions": {"Payload": {"type": "object"}},
        "paths": {
          "/users/{id}": {
            "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer"}],
            "post": {
              "parameters": [{"name": "body", "in": "body", "schema": {"$ref": "#/definitions/Payload"}}],
              "responses": {"200": {"description": "ok"}}
            }
          },
          "/form": {
            "post": {
              "consumes": ["application/x-www-form-urlencoded"],
              "parameters": [{"name": "name", "in": "formData", "required": true, "type": "string"}],
              "responses": {"200": {"description": "ok"}}
            }
          },
          "/upload": {
            "post": {
              "consumes": ["multipart/form-data"],
              "parameters": [{"name": "file", "in": "formData", "required": true, "type": "file"}],
              "responses": {"200": {"description": "ok"}}
            }
          }
        }
      }
      JSON

    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.size.should eq(3)
      request = String.new(result.flows[0].request.head)
      request.should contain("POST /v1/users/1 HTTP/1.1")
      request.should contain("Host: 127.0.0.1:18501\r\n")
      request.should contain("Content-Type: application/json\r\n")
      String.new(result.flows[0].request.body.not_nil!).should eq("{}")
      form_head = String.new(result.flows[1].request.head)
      form_head.should contain("Content-Type: application/x-www-form-urlencoded\r\n")
      String.new(result.flows[1].request.body.not_nil!).should eq("name=name")
      upload_head = String.new(result.flows[2].request.head)
      upload_head.should contain("Content-Type: multipart/form-data; boundary=gori-openapi-boundary\r\n")
      String.new(result.flows[2].request.body.not_nil!).should contain("filename=\"file\"")
    end
  end

  # A form requestBody imported with no body at all (and a multipart one with no boundary), a
  # JSON schema's properties came out as `{}`, and a media-type `example` was ignored.
  it "builds OpenAPI 3 form, multipart, JSON-property and example bodies" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"https://api.test"}],
       "components":{"schemas":{"User":{"type":"object","properties":{
         "name":{"type":"string"},"age":{"type":"integer"},"admin":{"type":"boolean","default":false},
         "role":{"type":"string","enum":["user","admin"]},"tags":{"type":"array"},
         "address":{"type":"object","properties":{"city":{"type":"string","example":"Seoul"}}},
         "self":{"$ref":"#/components/schemas/User"}}}}},
       "paths":{
         "/form":{"post":{"requestBody":{"content":{"application/x-www-form-urlencoded":{"schema":{
           "type":"object","properties":{"user":{"type":"string"},"n":{"type":"integer","example":7}}}}}},
           "responses":{"200":{"description":"OK"}}}},
         "/upload":{"post":{"requestBody":{"content":{"multipart/form-data":{"schema":{
           "type":"object","properties":{"note":{"type":"string"},"file":{"type":"string","format":"binary"}}}}}},
           "responses":{"200":{"description":"OK"}}}},
         "/json":{"post":{"requestBody":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/User"}}}},
           "responses":{"200":{"description":"OK"}}}},
         "/example":{"post":{"requestBody":{"content":{"application/json":{
           "schema":{"$ref":"#/components/schemas/User"},"example":{"name":"alice"}}}},
           "responses":{"200":{"description":"OK"}}}},
         "/examples":{"post":{"requestBody":{"content":{"application/x-www-form-urlencoded":{
           "examples":{"first":{"value":{"q":"a b","page":2}}}}}},
           "responses":{"200":{"description":"OK"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.skipped.should eq(0)
      by_path = result.flows.to_h { |f| {f.request.target, f.request} }

      form = by_path["/form"]
      String.new(form.head).should contain("Content-Type: application/x-www-form-urlencoded\r\n")
      String.new(form.body.not_nil!).should eq("user=user&n=7")

      upload = by_path["/upload"]
      String.new(upload.head).should contain("Content-Type: multipart/form-data; boundary=gori-openapi-boundary\r\n")
      multipart = String.new(upload.body.not_nil!)
      multipart.should contain(%(Content-Disposition: form-data; name="note"\r\n\r\nnote\r\n))
      multipart.should contain(%(name="file"; filename="file"\r\nContent-Type: application/octet-stream\r\n))
      multipart.should end_with("--gori-openapi-boundary--\r\n")

      user = JSON.parse(String.new(by_path["/json"].body.not_nil!))
      user["name"].should eq("name")
      user["age"].should eq(0)
      user["admin"].as_bool.should be_false
      user["role"].should eq("user")
      user["tags"].should eq(JSON.parse("[]"))
      user["address"].should eq(JSON.parse(%({"city":"Seoul"})))
      user["self"]["name"].should eq("name") # recursive: bounded, not endless

      String.new(by_path["/example"].body.not_nil!).should eq(%({"name":"alice"}))
      String.new(by_path["/examples"].body.not_nil!).should eq("q=a+b&page=2")
    end
  end

  it "reports remote refs without fetching them" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"https://api.example.test"}],"paths":{"/a":{"get":{
         "parameters":[{"$ref":"https://example.test/parameters.json#/Token"}],
         "responses":{"200":{"description":"ok"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      expect_raises(Gori::Error, /remote.*\$ref|\$ref.*remote/i) { Gori::Import::Oas.parse_file(path) }
    end
  end

  # The shape `Export::OpenApi` writes when a capture spans hosts: root lists every server,
  # and each path item names the one it was captured on.
  it "sends an operation to its path item's or its own servers over the root list" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"https://a.test"},{"url":"https://b.test"}],
       "paths":{"/only-b":{"servers":[{"url":"https://b.test"}],
                           "get":{"responses":{"200":{"description":"OK"}}},
                           "post":{"servers":[{"url":"https://c.test"}],"responses":{"200":{"description":"OK"}}}},
                "/root":{"get":{"responses":{"200":{"description":"OK"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.map { |f| {f.request.method, f.request.host} }.sort!.should eq(
        [{"GET", "a.test"}, {"GET", "b.test"}, {"POST", "c.test"}])
    end
  end

  it "keeps the root server for a relative or default-less templated path-level server" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"https://a.test"}],
       "paths":{"/rel":{"servers":[{"url":"/v2"}],"get":{"responses":{"200":{"description":"OK"}}}},
                "/tpl":{"get":{"servers":[{"url":"https://{region}.b.test","variables":{"region":{"description":"x"}}}],
                               "responses":{"200":{"description":"OK"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.skipped.should eq(0)
      result.flows.map(&.request.host).should eq(["a.test", "a.test"])
    end
  end

  # OpenAPI 3 requires every server variable to carry a `default`. Left templated, a root
  # `http://{host}:18371/{base}` skipped every operation as malformed with no reason, and a
  # `{base}` alone imported a literal `/{base}/items/1`.
  it "fills server url variables with their defaults" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"http://{host}:{port}/{base}",
                   "variables":{"host":{"default":"api.test"},"port":{"default":18371},
                                "base":{"default":"v2","enum":["v1","v2"]}}}],
       "paths":{"/items/{id}":{"get":{"parameters":[{"name":"id","in":"path","required":true,
                                                      "schema":{"type":"integer"}}],
                                       "responses":{"200":{"description":"OK"}}}},
                "/eu":{"get":{"servers":[{"url":"https://{region}.b.test","variables":{"region":{"default":"eu"}}}],
                              "responses":{"200":{"description":"OK"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.skipped.should eq(0)
      result.flows.map { |f| {f.request.host, f.request.port, f.request.target} }.should eq(
        [{"api.test", 18371, "/v2/items/1"}, {"eu.b.test", 443, "/eu"}])
    end
  end

  it "takes an enum's first member for a server variable that has no default" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"https://api.test/{base}","variables":{"base":{"enum":["v1","v2"]}}}],
       "paths":{"/a":{"get":{"responses":{"200":{"description":"OK"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.first.request.target.should eq("/v1/a")
    end
  end

  it "imports a form operation whose body schema is a remote $ref, without a body" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"https://api.test"}],
       "paths":{"/login":{"post":{"requestBody":{"content":{"application/x-www-form-urlencoded":
         {"schema":{"$ref":"schemas.yaml#/Login"}}}},"responses":{"200":{"description":"OK"}}}},
                "/a":{"get":{"responses":{"200":{"description":"OK"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.map(&.request.target).sort!.should eq(["/a", "/login"])
    end
  end

  it "names a root server variable that has no default instead of skipping every operation" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"https://api.test/{base}","variables":{"base":{"description":"x"}}}],
       "paths":{"/a":{"get":{"responses":{"200":{"description":"OK"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      expect_raises(Gori::Error, /\{base\} has no default/) { Gori::Import::Oas.parse_file(path) }
    end
  end

  it "resolves a percent-encoded $ref pointer" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"https://a.test"}],
       "paths":{"/users/{id}":{"get":{"responses":{"200":{"description":"OK"}}}},
                "/alias/{id}":{"$ref":"#/paths/~1users~1%7Bid%7D"}}}
      JSON
    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.skipped.should eq(0)
      result.flows.size.should eq(2)
    end
  end

  it "bounds local ref cycles and counts the affected operation as skipped" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"https://api.example.test"}],
       "components":{"parameters":{"A":{"$ref":"#/components/parameters/B"},
                                     "B":{"$ref":"#/components/parameters/A"}}},
       "paths":{"/a":{"get":{"parameters":[{"$ref":"#/components/parameters/A"}],
         "responses":{"200":{"description":"ok"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.should be_empty
      result.skipped.should eq(1)
    end
  end

  # `URI.parse` RAISES on a port an author can type by hand: one that overflows Int32 comes
  # back as `OverflowError`, a non-numeric one as `URI::Error`. Neither is a `Gori::Error`, so
  # both left `server_base` as a raw backtrace out of the CLI.
  it "names an unparseable servers[0].url instead of raising out of the importer" do
    ["https://api.example.test:99999999999999999999/v1", "https://api.example.test:abc/v1"].each do |url|
      body = <<-YAML
        openapi: 3.0.0
        info: {title: t, version: "1"}
        servers:
          - url: "#{url}"
        paths:
          /a:
            get:
              responses: {"200": {description: ok}}
        YAML
      with_spec(body, ".yaml") do |path|
        expect_raises(Gori::Error, /unparseable/) { Gori::Import::Oas.parse_file(path) }
      end
    end
  end

  # The YAML parses; the `to_json` in the same expression is what raises. A self-referential
  # anchor is legal YAML and yields a CYCLIC `YAML::Any`, which `to_json` walks until it hits
  # the stdlib's nesting guard — a `JSON::Error`, which the `YAML::ParseException` clause
  # never covered.
  it "reports a self-referential YAML anchor instead of crashing on the cycle" do
    with_spec("a: &anchor\n  b: *anchor\n", ".yaml") do |path|
      expect_raises(Gori::Error, /cannot be represented as JSON/) { Gori::Import::Oas.parse_file(path) }
    end
  end

  # `.inf` and `.nan` are legal YAML scalars an OpenAPI author writes by hand (`maximum: .inf`
  # in a schema is ordinary) and a deep-but-ACYCLIC spec trips the same nesting guard, so all
  # three arrive as `JSON::Error` too. The clause must not send the operator hunting for an
  # anchor that does not exist.
  it "does not blame an anchor for a value that merely has no JSON spelling" do
    {"maximum: .inf\n", "maximum: .nan\n"}.each do |body|
      with_spec(body, ".yaml") do |path|
        ex = expect_raises(Gori::Error, /cannot be represented as JSON/) { Gori::Import::Oas.parse_file(path) }
        ex.message.to_s.should_not contain("self-referential anchor (an alias")
      end
    end
  end

  # `YAML.parse` compares mapping keys while it builds the Hash, and two CYCLIC sequence keys
  # recurse in `YAML::Any#==` until the stack overflows: a SIGSEGV, which no clause can rescue.
  # So this example does not fail without the pre-scan — it takes the spec binary down.
  it "refuses cyclic anchors used as mapping keys before YAML.parse compares them" do
    body = "openapi: 3.0.0\npaths: {}\nx: {? &a [*a] : 1, ? &b [*b] : 2}\n"
    with_spec(body, ".yaml") do |path|
      expect_raises(Gori::Error, /mapping key that is not a string \(line 3\)/) { Gori::Import::Oas.parse_file(path) }
    end
  end

  it "refuses a non-string mapping key" do
    with_spec("openapi: 3.0.0\npaths: {}\nx: {? [1, 2] : 1}\n", ".yaml") do |path|
      expect_raises(Gori::Error, /mapping key that is not a string/) { Gori::Import::Oas.parse_file(path) }
    end
  end

  it "reports a YAML value the core schema cannot carry into JSON as the spec's error" do
    {"x: !!binary aGVsbG8=\n", "x: 2001-12-14t21:59:43.10+99:00\n"}.each do |body|
      with_spec("openapi: 3.0.0\npaths: {}\n#{body}", ".yaml") do |path|
        expect_raises(Gori::Error, /could not be read as YAML/) { Gori::Import::Oas.parse_file(path) }
      end
    end
  end

  it "still imports a spec that reuses an anchor as an ordinary value" do
    body = <<-YAML
      openapi: 3.0.0
      servers: [{url: "http://api.test"}]
      components: {schemas: {S: &s {type: string}}}
      paths:
        /a: {get: {responses: {"200": {description: ok}}, x-s: *s}}
        /b: {get: {responses: {"200": {description: ok}}, x-s: *s}}
      YAML
    with_spec(body, ".yaml") do |path|
      Gori::Import::Oas.parse_file(path).flows.size.should eq(2)
    end
  end

  it "still reports ordinary malformed YAML as bad YAML" do
    with_spec("openapi: [unclosed\n", ".yaml") do |path|
      expect_raises(Gori::Error, /not valid YAML/) { Gori::Import::Oas.parse_file(path) }
    end
  end
end

# `JSON.parse` passes raw bytes through unchecked, and the server-variable gsub is PCRE, which
# raises on invalid UTF-8 — outside the per-operation rescue.
describe "Gori::Import::Oas servers[0].url" do
  it "refuses a server URL that is not valid UTF-8 with a clean error" do
    body = %({"openapi":"3.0.0","servers":[{"url":"https://a\xc3{v}.test"}],"paths":{"/x":{"get":{}}}})
    with_spec(body, ".json") do |path|
      expect_raises(Gori::Error, /not valid UTF-8/) { Gori::Import::Oas.parse_file(path) }
    end
  end
end
