require "./request_parts"

module Gori
  module Export
    # A captured state-changing request as a self-submitting HTML CSRF PoC — the serializer
    # behind the TUI's "Copy as → CSRF PoC" row and `gori run show <id> --format csrf`. Burp's
    # "Generate CSRF PoC" engagement tool, as an `Export::*` module: pure request→text.
    #
    # HONESTY is the whole point (the CSRF analogue of Authorize's `drop_conditional_headers`).
    # A PoC that "fires" only because it replays a header a real cross-site page could never
    # send is a false demo. So this NEVER carries a header the browser controls or a page cannot
    # forge — Cookie (the browser attaches the victim's own, which is the entire mechanism),
    # Origin/Referer/Host (browser-set), Content-Length (framed for you), or any custom `X-…`
    # header (a form sends none; a `fetch` with one would trip CORS preflight and not fire
    # silently) — and it NAMES every header it dropped, in a visible comment, so the operator
    # reads what the attack actually relies on.
    #
    # Shape:
    #   * GET, or a POST whose body is form-urlencoded / multipart / empty → a real <form> with
    #     one hidden input per parameter, auto-submitting on load. This is a genuine cross-site
    #     request a browser will send with the victim's cookies.
    #   * anything else (JSON, other content-types, a non-GET/POST method) → a `fetch()` PoC
    #     with `credentials: "include"`, plus a note that it only fires if the endpoint accepts
    #     that content-type cross-site (a JSON Content-Type is not CORS-safelisted, so the
    #     browser preflights — many endpoints will refuse).
    module CsrfPoc
      # The PoC document for one request, or nil when there is no resolvable URL.
      def self.text(wire : String, target : String) : String?
        parts = RequestParts.from_wire(wire, target)
        parts ? document(parts) : nil
      end

      def self.document(parts : RequestParts::Parts) : String
        s = RequestParts.sendable(parts)
        method = (parts.method.empty? ? "GET" : parts.method).upcase
        ct = content_type_essence(s.headers)
        if form_capable?(method, ct, s.body)
          form_document(parts, method, ct, s.body)
        else
          fetch_document(parts, method, ct, s.body)
        end
      end

      # --- mode -----------------------------------------------------------------------------

      # Can a real HTML <form> reproduce this request? Only GET and POST are form methods, and a
      # POST body is form-shaped only when it is urlencoded, multipart, or absent. Everything
      # else (a JSON body, a PUT/DELETE) needs the fetch path.
      private def self.form_capable?(method : String, ct : String, body : String) : Bool
        return true if method == "GET"
        return false unless method == "POST"
        ct.empty? || ct == "application/x-www-form-urlencoded" || ct == "multipart/form-data" || body.empty?
      end

      # --- form path ------------------------------------------------------------------------

      private def self.form_document(parts : RequestParts::Parts, method : String,
                                     ct : String, body : String) : String
        multipart = ct == "multipart/form-data"
        # GET carries its parameters in the URL query; the inputs reproduce them, so the form
        # action is the URL WITHOUT the query (the browser rebuilds it from the inputs). A POST
        # keeps its full URL as the action and draws inputs from the body.
        action, fields =
          if method == "GET"
            {strip_query(parts.url), query_pairs(parts.url)}
          elsif multipart
            {parts.url, multipart_pairs(body, content_type_raw(parts))}
          else
            {parts.url, query_pairs_from_body(body)}
          end
        String.build do |b|
          b << "<!doctype html>\n<html>\n<head><meta charset=\"utf-8\"><title>CSRF PoC</title></head>\n"
          b << "<!-- CSRF PoC for " << html_comment_safe("#{method} #{parts.url}") << ", generated by gori. -->\n"
          # Content-Type is carried by the form's own enctype — but only when the enctype can
          # SPELL the captured one. A form has two (urlencoded, multipart) and a GET form sends
          # no body at all, so a `Content-Type: application/json` POST with an EMPTY body — which
          # `form_capable?` sends down this path on purpose, because a form CAN make that request,
          # just not under that content type — goes out urlencoded. Counting it as carried told
          # the operator the demo relied on a header it had in fact replaced; it is dropped like
          # any other, and named.
          carried = method == "POST" &&
                    (multipart || ct.empty? || ct == "application/x-www-form-urlencoded")
          dropped_headers_comment(b, parts, carried: carried ? "content-type" : nil)
          b << "<body onload=\"document.forms[0].submit()\">\n"
          b << "  <form action=\"" << attr(action) << "\" method=\"" << (method == "GET" ? "GET" : "POST") << "\""
          b << " enctype=\"multipart/form-data\"" if multipart
          b << ">\n"
          fields.each do |(name, value, note)|
            if note
              b << "    <!-- " << html_comment_safe(note) << " -->\n"
            end
            b << "    <input type=\"hidden\" name=\"" << attr(name) << "\" value=\"" << attr(value) << "\">\n"
          end
          b << "    <input type=\"submit\" value=\"Submit\">\n"
          b << "  </form>\n</body>\n</html>\n"
        end
      end

      # --- fetch path -----------------------------------------------------------------------

      private def self.fetch_document(parts : RequestParts::Parts, method : String,
                                      ct : String, body : String) : String
        String.build do |b|
          b << "<!doctype html>\n<html>\n<head><meta charset=\"utf-8\"><title>CSRF PoC</title></head>\n"
          b << "<!-- CSRF PoC for " << html_comment_safe("#{method} #{parts.url}") << ", generated by gori. -->\n"
          b << "<!-- fetch() PoC: this body is not form-encodable, so a <form> cannot reproduce it. -->\n"
          b << "<!-- It fires ONLY if the endpoint accepts this content-type cross-site — a non-safelisted -->\n"
          b << "<!-- Content-Type (e.g. application/json) triggers a CORS preflight the endpoint may refuse. -->\n"
          dropped_headers_comment(b, parts, carried: ct.empty? ? nil : "content-type")
          b << "<body>\n<script>\n"
          b << "fetch(" << jsurl(Escape.percent_encode_non_ascii(parts.url)) << ", {\n"
          b << "  method: " << jsstr(method) << ",\n"
          b << "  credentials: \"include\",\n"
          unless ct.empty?
            b << "  headers: { \"Content-Type\": " << jsstr(content_type_raw(parts)) << " },\n"
          end
          unless body.empty?
            # A non-UTF-8 body rides as a Uint8Array (exact bytes); a string body would have fetch
            # re-encode a high byte to two — the same footgun `Export::JsFetch` guards. And a
            # GET/HEAD carries no body at all: the Request constructor throws rather than
            # ignoring it, so the PoC would fire nothing. (`form_capable?` sends every GET down
            # the form path, so only a captured HEAD-with-a-body reaches this.)
            if method == "HEAD"
              b << "  // body omitted: fetch() refuses a body on a GET/HEAD request, so the\n"
              b << "  // captured " << body.bytesize << " bytes cannot ride — see --format raw.\n"
            elsif body.valid_encoding?
              b << "  body: " << jstext(body) << ",\n"
            else
              b << "  // body is not valid UTF-8; sent as raw bytes so the endpoint gets it exactly.\n"
              b << "  body: " << js_bytes(body) << ",\n"
            end
          end
          # No `mode: "no-cors"`: that mode would let the request fire, but the browser silently
          # STRIPS a non-safelisted Content-Type under it, so the endpoint would receive a
          # DIFFERENT content-type than the capture — a false demo. A default (cors) fetch keeps
          # the header and preflights instead, which fires only if the endpoint truly opts in.
          b << "});\n</script>\n</body>\n</html>\n"
        end
      end

      # --- dropped-headers honesty ----------------------------------------------------------

      # The visible comment naming every header this PoC did NOT carry, and why. `carried` is the
      # one header the fetch path keeps (Content-Type) so it is not listed as dropped. When
      # nothing was dropped the comment still prints, saying so — silence would read as "there
      # was nothing to drop", which is a different (and usually wrong) claim.
      private def self.dropped_headers_comment(b : IO, parts : RequestParts::Parts, carried : String?) : Nil
        dropped = [] of String
        seen = Set(String).new
        parts.headers.each do |(name, _)|
          down = name.downcase
          next if carried && down == carried
          next if seen.includes?(down)
          seen << down
          dropped << name
        end
        b << "<!-- Headers a cross-site page CANNOT forge — dropped so this demo reflects what an\n"
        b << "     attacker page can actually send (it relies on the victim's ambient cookies): "
        b << (dropped.empty? ? "none" : html_comment_safe(dropped.join(", ")))
        b << " -->\n"
      end

      # --- parameter extraction -------------------------------------------------------------

      # {name, value, note?} triples. `note` rides a file part the PoC cannot pre-fill.
      private def self.query_pairs(url : String) : Array({String, String, String?})
        q = url.index('?')
        q ? split_form(url[(q + 1)..]) : [] of {String, String, String?}
      end

      private def self.query_pairs_from_body(body : String) : Array({String, String, String?})
        split_form(body)
      end

      # `a=1&b=2` → decoded {name, value, nil} pairs. Values are percent/`+`-decoded so the
      # browser re-encodes them back on submit; a bare `a` (no `=`) is a name with an empty value.
      private def self.split_form(s : String) : Array({String, String, String?})
        pairs = [] of {String, String, String?}
        return pairs if s.empty?
        s.split('&').each do |pair|
          next if pair.empty?
          eq = pair.index('=')
          if eq
            pairs << {percent_decode(pair[0, eq]), percent_decode(pair[(eq + 1)..]), nil}
          else
            pairs << {percent_decode(pair), "", nil}
          end
        end
        pairs
      end

      # multipart/form-data body → {name, value, note?} per part. Text parts contribute their
      # value; a file part (Content-Disposition carries `filename`) contributes an empty value
      # and a note, because no HTML can pre-fill a file input. `raw_ct` is the FULL Content-Type
      # (`multipart/form-data; boundary=…`) — the boundary is a parameter, so it is read here,
      # falling back to the body's own first delimiter when the header omitted it.
      private def self.multipart_pairs(body : String, raw_ct : String) : Array({String, String, String?})
        pairs = [] of {String, String, String?}
        boundary = multipart_boundary(body, raw_ct)
        return pairs unless boundary
        delim = "--#{boundary}"
        body.split(delim).each do |raw|
          seg = raw
          next if seg.empty? || seg.starts_with?("--") # preamble / closing marker
          seg = seg.lstrip("\r\n")
          sep = seg.index("\r\n\r\n") || seg.index("\n\n")
          next unless sep
          head = seg[0, sep]
          # Exactly ONE trailing newline is the framing before the next delimiter; chopping both
          # a CRLF and an LF (`.rchop("\r\n").rchop("\n")`) would also eat a value's own trailing
          # LF (`line1\nline2\n` on the wire is `…\n\r\n` → must come back as `…\n`, not `…`).
          value = strip_one_trailing_newline(seg[(sep + (seg[sep, 2] == "\r\n" ? 4 : 2))..])
          name = disposition_field(head, "name")
          next unless name
          filename = disposition_field(head, "filename")
          if filename
            pairs << {name, "", "file part '#{filename}' (#{value.bytesize} bytes) — a PoC cannot pre-fill a file input"}
          else
            pairs << {name, value, nil}
          end
        end
        pairs
      end

      # The boundary from the Content-Type params (`multipart/form-data; boundary=…`), else the
      # one the body itself opens with (`--boundary` on the first line), else nil.
      private def self.multipart_boundary(body : String, raw_ct : String) : String?
        if b = disposition_field(raw_ct, "boundary")
          return b unless b.empty?
        end
        first = body.lstrip("\r\n")
        return nil unless first.starts_with?("--")
        eol = first.index("\r\n") || first.index("\n")
        line = eol ? first[0, eol] : first
        candidate = line[2..].rstrip
        candidate.empty? ? nil : candidate.rchop("--")
      end

      # --- content-type ---------------------------------------------------------------------

      # The lowercased media type with parameters stripped (`application/json; charset=utf-8` →
      # `application/json`), or "" when absent.
      private def self.content_type_essence(headers : Array({String, String})) : String
        raw = content_type_of(headers)
        return "" unless raw
        semi = raw.index(';')
        (semi ? raw[0, semi] : raw).strip.downcase
      end

      private def self.content_type_raw(parts : RequestParts::Parts) : String
        content_type_of(parts.headers) || ""
      end

      private def self.content_type_of(headers : Array({String, String})) : String?
        headers.each { |(n, v)| return v if n.downcase == "content-type" }
        nil
      end

      # --- byte helpers ---------------------------------------------------------------------

      # A URL with any `?query` cut off.
      private def self.strip_query(url : String) : String
        q = url.index('?')
        q ? url[0, q] : url
      end

      # The `field="…"` (or `field=token`) value out of a MIME header line, case-insensitive. The
      # match must be at a PARAMETER BOUNDARY — a naive `index("name=")` finds the `name=` inside
      # `filename=`, so a part listing `filename` before `name` would take the filename as the
      # field name. Only a `field=` whose preceding byte is a separator (`;`, whitespace, `:`, a
      # line break) or the start of the string counts.
      private def self.disposition_field(head : String, field : String) : String?
        needle = "#{field}=".downcase
        hay = head.downcase
        start = 0
        while idx = hay.index(needle, start)
          before = idx == 0 ? ';' : hay[idx - 1]
          if boundary_byte?(before)
            rest = head[(idx + field.size + 1)..]
            if rest.starts_with?('"')
              close = rest.index('"', 1)
              return close ? rest[1, close - 1] : nil
            else
              m = rest.index(';') || rest.index("\r") || rest.index("\n")
              return (m ? rest[0, m] : rest).strip
            end
          end
          start = idx + 1
        end
        nil
      end

      private def self.boundary_byte?(c : Char) : Bool
        c == ';' || c == ' ' || c == '\t' || c == ':' || c == '\r' || c == '\n'
      end

      # `s` with ONE trailing newline removed — a CRLF taken whole, else a lone LF — and nothing
      # when it ends in neither. The single framing newline before a multipart delimiter.
      private def self.strip_one_trailing_newline(s : String) : String
        return s[0, s.bytesize - 2] if s.ends_with?("\r\n")
        return s[0, s.bytesize - 1] if s.ends_with?("\n")
        s
      end

      # Percent-decode a urlencoded token: `+` → space, `%XX` → that byte, everything else
      # verbatim. Byte-wise so a non-ASCII value survives; invalid `%XX` is left literal.
      private def self.percent_decode(s : String) : String
        bytes = s.to_slice
        io = IO::Memory.new(bytes.size)
        i = 0
        while i < bytes.size
          b = bytes[i]
          if b == 0x2b_u8 # +
            io.write_byte(0x20_u8)
            i += 1
          elsif b == 0x25_u8 && i + 2 < bytes.size && (hi = hex(bytes[i + 1])) && (lo = hex(bytes[i + 2]))
            io.write_byte((hi << 4 | lo).to_u8)
            i += 3
          else
            io.write_byte(b)
            i += 1
          end
        end
        String.new(io.to_slice)
      end

      private def self.hex(b : UInt8) : Int32?
        case b
        when 0x30_u8..0x39_u8 then (b - 0x30_u8).to_i
        when 0x41_u8..0x46_u8 then (b - 0x41_u8 + 10).to_i
        when 0x61_u8..0x66_u8 then (b - 0x61_u8 + 10).to_i
        end
      end

      # HTML attribute-value escaping (inside "…"): the five that matter, so a value cannot
      # break out of the attribute or the tag.
      private def self.attr(s : String) : String
        s.gsub('&', "&amp;").gsub('<', "&lt;").gsub('>', "&gt;").gsub('"', "&quot;").gsub('\'', "&#39;")
      end

      # Text safe to sit inside an HTML comment: `--` (which would close the comment early) and a
      # literal `>` right after it are neutralised. Comments carry only gori's own prose plus
      # header/param NAMES, so this is a guard, not lossless round-tripping.
      private def self.html_comment_safe(s : String) : String
        s.gsub("--", "- -").gsub('\n', ' ').gsub('\r', ' ')
      end

      # A JS double-quoted string, byte-safe with `\xNN` — the fetch path's method and its
      # Content-Type, where a code unit IS a byte on the wire. `<` and `>` are neutralised BEFORE
      # the shared escaper so nothing can close the surrounding `<script>`; every other byte goes
      # through `Export::Escape`.
      private def self.jsstr(s : String) : String
        String.build do |b|
          b << '"'
          s.to_slice.each do |byte|
            case byte
            when 0x3c_u8 then b << "\\x3c" # < — never let a body close the <script>
            when 0x3e_u8 then b << "\\x3e"
            else              Escape.double_quoted_byte(b, byte)
            end
          end
          b << '"'
        end
      end

      # The same literal for text fetch RE-ENCODES as UTF-8 — the body. Character-wise, because a
      # `\xNN` per UTF-8 byte is one code unit each and fetch encodes each of those to two bytes,
      # so the endpoint would receive a body the capture never sent — the footgun the Uint8Array
      # arm below guards for a body that is not valid UTF-8, on the arm that IS. `Export::JsFetch`
      # draws the same line.
      private def self.jstext(s : String) : String
        String.build do |b|
          b << '"'
          s.each_char do |ch|
            case ch
            when '<' then b << "\\x3c"
            when '>' then b << "\\x3e"
            else          Escape.double_quoted_char(b, ch)
            end
          end
          b << '"'
        end
      end

      # The URL literal. Character-wise like `jstext` — after `percent_encode_non_ascii` the only
      # non-ASCII bytes left are the AUTHORITY's, and a `\xNN` per UTF-8 byte hands the URL parser
      # one Latin-1 codepoint per byte to IDNA-encode, which is a different host than the capture.
      # Not `Escape.double_quoted_url`: this literal sits inside a `<script>`, so `<`/`>` still
      # have to be neutralised before anything else. A URL that is not valid UTF-8 has no text
      # spelling and falls back to the byte form rather than being scrubbed to U+FFFD.
      private def self.jsurl(url : String) : String
        url.valid_encoding? ? jstext(url) : jsstr(url)
      end

      # A JS Uint8Array literal (`new Uint8Array([255, …])`) — the fetch path's body when it is
      # not valid UTF-8, so the endpoint receives the captured bytes rather than the two bytes a
      # high code unit re-encodes to when fetch UTF-8-encodes a string body.
      private def self.js_bytes(s : String) : String
        "new Uint8Array([#{s.to_slice.join(", ")}])"
      end
    end
  end
end
