# gori — free/open-source TUI web proxy (MITM).
#
# This is the library entrypoint. The executable's behaviour lives in
# `Gori::CLI.run` (added in a later build step); for now this file only
# establishes the module, version, and the single base error type.
module Gori
  VERSION = "0.8.0"

  # Canonical project home — surfaced in the TUI Help → About page (and reusable
  # by the CLI/about screens). Kept beside VERSION as the project's identity.
  REPOSITORY_URL = "https://github.com/hahwul/gori"

  # Single base error for the whole project. Subtype only when a `rescue`
  # actually needs to discriminate (P0 — don't build a hierarchy speculatively).
  class Error < Exception
  end
end

require "./gori/win32_signal"
require "./gori/json_nesting"
require "./gori/local_time"
require "./gori/proxy/socks5"
require "./gori/proxy/codec/message"
require "./gori/proxy/codec/http1"
require "./gori/alt_svc"
require "./gori/proxy/codec/body"
require "./gori/proxy/codec/content_decode"
require "./gori/proxy/h2/frame"
require "./gori/proxy/h2/hpack"
require "./gori/proxy/h2/grpc"
require "./gori/protobuf"
require "./gori/protobuf/schema"
require "./gori/protobuf/lens"
require "./gori/protobuf/encoder"
require "./gori/binary_document"
require "./gori/msgpack"
require "./gori/cbor"
require "./gori/proxy/h2/assembler"
require "./gori/proxy/h2/relay"
require "./gori/proxy/prefix_io"
require "./gori/store"
require "./gori/protobuf/schemas"
require "./gori/links"
require "./gori/evidence"
require "./gori/cvss"
require "./gori/rule_set_change"
require "./gori/config_log"
require "./gori/rules"
require "./gori/bindings"
require "./gori/session_from_flow"
require "./gori/scope"
require "./gori/outbound"
require "./gori/interceptor"
require "./gori/flow_mapper"
require "./gori/proxy/server"
require "./gori/repeater/engine"
require "./gori/repeater/h2_engine"
require "./gori/repeater/ws_engine"
require "./gori/repeater/ws_frame_spec"
require "./gori/repeater/sender"
require "./gori/repeater/plan"
require "./gori/repeater/send_persistence"
require "./gori/repeater/history_record"
require "./gori/retest"
require "./gori/retest/live_backend"
require "./gori/repeater/diff"
require "./gori/fuzz"
require "./gori/miner"
require "./gori/sequencer"
require "./gori/discover"
require "./gori/authorize/plan"
require "./gori/oast"
require "./gori/probe"
require "./gori/peer_notices"
require "./gori/mcp"
require "./gori/proxy/tls/cert_authority"
require "./gori/proxy/tls/tunnel"
require "./gori/verb"
require "./gori/verbs/core"
require "./gori/verbs/import"
require "./gori/verbs/history"
require "./gori/import"
require "./gori/export"
require "./gori/verbs/sitemap"
require "./gori/verbs/discover"
require "./gori/verbs/oast"
require "./gori/verbs/issues"
require "./gori/verbs/probe"
require "./gori/verbs/sequencer"
require "./gori/probe_query"
require "./gori/fuzzy"
require "./gori/paths"
require "./gori/tty_path"
require "./gori/settings"
require "./gori/env"
require "./gori/env_migration"
require "./gori/env_migration/globals"
require "./gori/env_migration/store"
require "./gori/hotkeys"
require "./gori/browser"
require "./gori/config"
require "./gori/update"
require "./gori/decoder"
require "./gori/pretty"
require "./gori/sse"
require "./gori/proto"
require "./gori/saml"
require "./gori/jwt"
require "./gori/cookie"
require "./gori/graphql"
require "./gori/graphql_ws"
require "./gori/ws_proto"
require "./gori/form_data"
require "./gori/params"
require "./gori/decoded_view"
require "./gori/tolerance"
require "./gori/sitemap"
require "./gori/param_inventory"
require "./gori/js_refs"
require "./gori/diff"
require "./gori/tui"
require "./gori/app"
require "./gori/cli"
